---
# tasks file for firewall

- name: Permit TCP
  ansible.posix.firewalld:
    port: 25565/tcp
    permanent: true
    state: enabled

- name: Permit UDP
  ansible.posix.firewalld:
    port: 25565/udp
    permanent: true
    state: enabled
