---
- name: Create Minecraft directory
  file:
    path: /opt/minecraft
    state: directory

- name: Download Minecraft server JAR
  get_url:
    url: "https://piston-data.mojang.com/v1/objects/8dd1a28015f51b1803213892b50b7b4fc76e594d/server.jar"
    dest: /opt/minecraft/server.jar
