---
# tasks file for minecraft

- name: Create Minecraft directory
  file:
    path: /opt/minecraft
    state: directory

- name: Download Minecraft server JAR
  get_url:
    url: "https://piston-data.mojang.com/v1/objects/8dd1a28015f51b1803213892b50b7b4fc76e594d/server.jar"
    dest: /opt/minecraft/server.jar
  vars:
    minecraft_version: "server-1.17.1"  # Versão do Minecraft desejada

- name: Accept Minecraft EULA
  copy:
    content: "eula=true\n"
    dest: /opt/minecraft/eula.txt
  when: not minecraft_eula_accepted|default(false)|bool
